name: Periodic Snail

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run_snail_script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.13'
      - run: |
          python -m pip install --upgrade pip
          pip install -r snails/404remover/requirements.txt
      - run: python snails/404remover/main.py
        env:
          OSM_ACCESS_TOKEN: ${{ secrets.OSM_ACCESS_TOKEN }}
